from . import res_company
from . import category
from . import planes
from . import plan_servicio
from . import product_template
from . import account_move
from . import purchase_order
from . import soa_integration_api
from . import account_analytic_account
from . import res_partner