from odoo import api, fields, models

#Display amount in words in Sale order
class AccountMove(models.Model):

    _inherit = 'account.move'

    def _compute_amount2words(self):
        for rec in self:
                rec.amount_words = str(rec.currency_id.amount_to_text(rec.amount_total))

    amount_words = fields.Char(string="Total amount in words: ", help=
        "Total amount in words is automatically generated by the system", compute='_compute_amount2words')